# fly.toml app configuration file generated for solitary-breeze-9512 on 2023-07-06T23:50:28+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "solitary-breeze-9512"
primary_region = "arn"
console_command = "/code/manage.py shell"

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
